linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gosec

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - third_party/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
