global:
  # Runtime environment: development, testing, production
  env: development
  # Log level: debug, info, warn, error
  log_level: info
  # Monitoring metrics configuration
  metrics:
    enabled: true
    port: 9090

fil:
  # Lotus API configuration
  lotus:
    # Lotus API address
    api_url: "http://127.0.0.1:1234/rpc/v1"
    # Lotus API Token, can be set via environment variable THCTL_FIL_LOTUS_TOKEN
    token: ""
    # API request timeout
    timeout: 30s
  # Filecoin services configuration
  services:
    # Sector penalty service configuration
    sectors_penalty:
      # Service port
      port: 8099
      # API rate limit (requests per minute)
      rate_limit: 100
      # Cache TTL
      cache_ttl: 300s

storage:
  # AWS S3 configuration
  s3:
    region: "us-west-2"
    access_key: ""  # Can be set via THCTL_S3_ACCESS_KEY
    secret_key: ""  # Can be set via THCTL_S3_SECRET_KEY
    endpoint: ""    # Optional, for S3-compatible services
    bucket_name: "" # Default bucket name

  # Aliyun OSS configuration
  oss:
    region: "cn-hangzhou"
    access_key: ""  # Can be set via THCTL_OSS_ACCESS_KEY
    secret_key: ""  # Can be set via THCTL_OSS_SECRET_KEY
    endpoint: "oss-cn-hangzhou.aliyuncs.com"  # OSS endpoint
    bucket_name: "" # Default bucket name
    internal: false # Use internal endpoint

  # Tencent COS configuration
  cos:
    region: "ap-guangzhou"
    access_key: ""  # Can be set via THCTL_COS_ACCESS_KEY
    secret_key: ""  # Can be set via THCTL_COS_SECRET_KEY
    endpoint: ""    # Optional COS endpoint
    bucket_name: "" # Default bucket name
    app_id: ""      # Tencent Cloud APP ID

log:
  # Log level: debug, info, warn, error
  level: "info"
  # Log file path (empty for stdout)
  file: ""
  # Log format: text, json
  format: "text"

cli:
  # Default output format: table, json, csv
  default_output: table
  # Enable colored output
  color_enabled: true

# Environment variable mappings:
# THCTL_GLOBAL_ENV              -> global.env
# THCTL_GLOBAL_LOG_LEVEL        -> global.log_level
# THCTL_FIL_LOTUS_API_URL      -> fil.lotus.api_url
# THCTL_FIL_LOTUS_TOKEN        -> fil.lotus.token
# THCTL_FIL_SERVICES_SECTORS_PENALTY_PORT -> fil.services.sectors_penalty.port